2023-12-05 17:28:56,607 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:28:56,608 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/giZYlHwKND
2023-12-05 17:28:56,608 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/giZYlHwKND
2023-12-05 17:28:56,608 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:28:56,608 - INFO - Starting Flet View app...
2023-12-05 17:28:56,608 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:28:56,809 - INFO - Session started: 
2023-12-05 17:51:39,002 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:51:39,003 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/IjSCiOXnjH
2023-12-05 17:51:39,003 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/IjSCiOXnjH
2023-12-05 17:51:39,004 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:51:39,004 - INFO - Starting Flet View app...
2023-12-05 17:51:39,004 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:51:39,260 - INFO - Session started: 
2023-12-05 17:51:45,629 - ERROR - TipsViewWithBackButton.process() missing 1 required positional argument: 'page'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TipsViewWithBackButton.process() missing 1 required positional argument: 'page'
2023-12-05 17:52:06,400 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:52:06,401 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/RJFSbaMItv
2023-12-05 17:52:06,401 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/RJFSbaMItv
2023-12-05 17:52:06,401 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:52:06,401 - INFO - Starting Flet View app...
2023-12-05 17:52:06,401 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:52:06,608 - INFO - Session started: 
2023-12-05 17:52:08,520 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 17:52:10,005 - ERROR - unsupported operand type(s) for +: 'View' and 'str'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/_build_in_b.py", line 16, in process
    url = page.views[-1] + "/tips"
          ~~~~~~~~~~~~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for +: 'View' and 'str'
2023-12-05 17:52:28,074 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:52:28,075 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/rGWvfCGcDH
2023-12-05 17:52:28,075 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/rGWvfCGcDH
2023-12-05 17:52:28,075 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:52:28,075 - INFO - Starting Flet View app...
2023-12-05 17:52:28,075 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:52:28,283 - INFO - Session started: 
2023-12-05 17:52:30,184 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 17:53:00,915 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:53:00,916 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ZKLEKVwjDK
2023-12-05 17:53:00,916 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ZKLEKVwjDK
2023-12-05 17:53:00,916 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:53:00,917 - INFO - Starting Flet View app...
2023-12-05 17:53:00,917 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:53:01,116 - INFO - Session started: 
2023-12-05 17:55:14,254 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:55:14,255 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/gbwHaxHTFX
2023-12-05 17:55:14,255 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/gbwHaxHTFX
2023-12-05 17:55:14,255 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:55:14,255 - INFO - Starting Flet View app...
2023-12-05 17:55:14,255 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:55:14,463 - INFO - Session started: 
2023-12-05 17:55:16,385 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 18:44:20,226 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 18:44:20,227 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/envbAGcXrF
2023-12-05 18:44:20,227 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/envbAGcXrF
2023-12-05 18:44:20,227 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 18:44:20,228 - INFO - Starting Flet View app...
2023-12-05 18:44:20,228 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 18:44:20,472 - INFO - Session started: 
2023-12-05 18:44:48,598 - ERROR - 'list_iterator' object has no attribute 'keys'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugins.py", line 234, in process
    columns = data.keys
              ^^^^^^^^^
AttributeError: 'list_iterator' object has no attribute 'keys'
2023-12-05 18:47:43,619 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 18:51:11,797 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 18:51:11,798 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/KJeJfAgiqm
2023-12-05 18:51:11,798 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/KJeJfAgiqm
2023-12-05 18:51:11,798 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 18:51:11,798 - INFO - Starting Flet View app...
2023-12-05 18:51:11,798 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 18:51:12,012 - INFO - Session started: 
2023-12-05 19:05:08,480 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:05:08,480 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/lczRLYYUjl
2023-12-05 19:05:08,481 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/lczRLYYUjl
2023-12-05 19:05:08,481 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:05:08,481 - INFO - Starting Flet View app...
2023-12-05 19:05:08,481 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:05:08,708 - INFO - Session started: 
2023-12-05 19:08:48,590 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:08:48,592 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/EiPMPnJMzU
2023-12-05 19:08:48,592 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/EiPMPnJMzU
2023-12-05 19:08:48,592 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:08:48,592 - INFO - Starting Flet View app...
2023-12-05 19:08:48,592 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:08:48,787 - INFO - Session started: 
2023-12-05 19:08:51,446 - ERROR - name 'partial' is not defined
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/_base.py", line 73, in process
    func = partial(
           ^^^^^^^
NameError: name 'partial' is not defined
2023-12-05 19:19:43,360 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:19:43,362 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/yLNltOoXyB
2023-12-05 19:19:43,362 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/yLNltOoXyB
2023-12-05 19:19:43,362 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:19:43,362 - INFO - Starting Flet View app...
2023-12-05 19:19:43,363 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:19:43,578 - INFO - Session started: 
2023-12-05 19:19:43,578 - ERROR - '_index'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 30, in run
    plugin = icls.PLUGINS[plugin_name]
             ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '_index'
2023-12-05 19:22:31,689 - ERROR - [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 123, in process
    self._load("", path=data)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 128, in _load
    for item in os.listdir(f):
                ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''
2023-12-05 19:22:31,690 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:22:31,691 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/tDyDizwhZV
2023-12-05 19:22:31,692 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/tDyDizwhZV
2023-12-05 19:22:31,692 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:22:31,692 - INFO - Starting Flet View app...
2023-12-05 19:22:31,692 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:22:31,899 - INFO - Session started: 
2023-12-05 19:22:31,899 - ERROR - '_index'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 30, in run
    plugin = icls.PLUGINS[plugin_name]
             ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '_index'
2023-12-05 19:24:21,920 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:24:21,920 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/sUAIoKvuxv
2023-12-05 19:24:21,921 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/sUAIoKvuxv
2023-12-05 19:24:21,921 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:24:21,921 - INFO - Starting Flet View app...
2023-12-05 19:24:21,921 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:24:22,132 - INFO - Session started: 
2023-12-05 19:24:32,038 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 19:25:18,747 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:25:18,747 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/zzdCkCKyrC
2023-12-05 19:25:18,747 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/zzdCkCKyrC
2023-12-05 19:25:18,747 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:25:18,747 - INFO - Starting Flet View app...
2023-12-05 19:25:18,747 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:25:18,960 - INFO - Session started: 
2023-12-05 19:25:18,960 - ERROR - '_index'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 30, in run
    plugin = icls.PLUGINS[plugin_name]
             ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '_index'
2023-12-05 19:27:54,307 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:27:54,308 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/aMSFfSbQvo
2023-12-05 19:27:54,309 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/aMSFfSbQvo
2023-12-05 19:27:54,309 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:27:54,309 - INFO - Starting Flet View app...
2023-12-05 19:27:54,309 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:27:54,502 - INFO - Session started: 
2023-12-05 19:32:42,939 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:32:42,940 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/VeaPgrgHWS
2023-12-05 19:32:42,940 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/VeaPgrgHWS
2023-12-05 19:32:42,940 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:32:42,940 - INFO - Starting Flet View app...
2023-12-05 19:32:42,940 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:32:43,205 - INFO - Session started: 
2023-12-05 19:33:00,355 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:33:00,356 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/vzfxmXjKJb
2023-12-05 19:33:00,356 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/vzfxmXjKJb
2023-12-05 19:33:00,356 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:33:00,356 - INFO - Starting Flet View app...
2023-12-05 19:33:00,357 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:33:00,572 - INFO - Session started: 
2023-12-05 19:33:38,331 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:33:38,331 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ntAZgfaqRN
2023-12-05 19:33:38,331 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ntAZgfaqRN
2023-12-05 19:33:38,331 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:33:38,331 - INFO - Starting Flet View app...
2023-12-05 19:33:38,332 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:33:38,543 - INFO - Session started: 
2023-12-05 19:35:40,639 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:35:40,640 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/SHEBacCHls
2023-12-05 19:35:40,640 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/SHEBacCHls
2023-12-05 19:35:40,640 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:35:40,640 - INFO - Starting Flet View app...
2023-12-05 19:35:40,640 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:35:40,920 - INFO - Session started: 
